### ISSUE TITLE
Feature request: Collect cancelled

### ISSUE THREAD

**Issue by jeaz** [TekNoLogic/NutCounter#1]
Hey,

I find this addon the best for tracking auctions, but I'd love to it collect (and maybe track as well) all cancelled auctions.
I sell lots of glyphs on the auction house and have to cancel them a few times a day due to undercut, and when you have 100ish of auctions it takes some time. And it could also be good to see how many times you have cancelled compared to sold an item.

Also, a minor thing. It could maybe be good to move the buttons as Blizzard since 3.2 has been giving you a text msg where the buttons are if you have lots of incoming mail. Not major, just cosmetic.

**Comment by tekkub** [comment]
I really have no plans for support cancelled auctions, sorry.

**Comment by jeaz** [comment]
Not even a collect button? Nvm the tracking, but the mass collection from inbox? 
Since using more than one mail-addon at the same time works quite poorly since the buttons are usually at the same places.

EDIT: Ok, I sorted an extra button myself and moved them all to the bottom, away from the over mailbox limit warning. First time I'm doing stuff like this, but hope it's ok. Can upload it somewhere if you want.

**Comment by tekkub** [comment]
The reason for the buttons IS the tracking, you have to throttle the rate at which you open stuff to get info.  So if I'm not tracking, there's really no point in the button either.
